import {useRef,useState} from 'react';
import {owner,services,budgets} from '../data';
export default function Contact(){const [state,setState]=useState({type:'idle',message:''});const busy=useRef(false);const status=useRef(null);
 async function submit(e){e.preventDefault();if(busy.current)return;const form=e.currentTarget;const fields=new FormData(form);if(fields.get('botcheck'))return;const key=import.meta.env.VITE_WEB3FORMS_KEY?.trim();
 if(!key){setState({type:'error',message:'The contact form is not connected yet. Please email me or use WhatsApp to discuss your project.'});return;}
 if(!String(fields.get('name')).trim()||!String(fields.get('message')).trim()){setState({type:'error',message:'Please enter your name and a short project description.'});return;}
 busy.current=true;setState({type:'loading',message:'Sending your project details…'});const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),15000);
 try{const response=await fetch('https://api.web3forms.com/submit',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({...Object.fromEntries(fields),access_key:key,subject:'New portfolio project enquiry',from_name:'Vijay Portfolio',replyto:fields.get('email')}),signal:controller.signal});const result=await response.json();if(!response.ok||!result.success)throw new Error('Submission failed');form.reset();setState({type:'success',message:'Thank you! Your project details have been sent. I’ll reply by email.'});}catch{setState({type:'error',message:'I couldn’t confirm delivery. Please try again, or contact me directly by email or WhatsApp.'});}finally{clearTimeout(timer);busy.current=false;}}
 return <section id="contact" className="contact-section"><div className="shell section contact-grid"><div><span className="eyebrow">06 / LET’S BUILD SOMETHING USEFUL</span><h2>Your next chapter<br/>starts with<br/><em>a conversation.</em></h2><p>Have a project in mind? Tell me what your business needs. We’ll work out the next step together.</p><a className="contact-email" href={'mailto:'+owner.email}>{owner.email}</a><a className="phone-link" href="tel:+918921330633">{owner.phone}</a><a className="button outline" href={owner.whatsapp+'?text='+encodeURIComponent('Hi Vijay, I’d like to discuss a website project.')} target="_blank" rel="noopener noreferrer">Chat on WhatsApp</a><div className="socials"><a href={owner.github} target="_blank" rel="noopener noreferrer">GitHub</a><a href={owner.linkedin} target="_blank" rel="noopener noreferrer">LinkedIn</a></div></div><form onSubmit={submit} className="contact-form"><h3>Tell me about your project.</h3><p className="form-intro">A few details are all we need to get started.</p><div className="form-row"><label>Your name <span>*</span><input name="name" autoComplete="name" required maxLength="100" placeholder="Your name"/></label><label>Email address <span>*</span><input type="email" name="email" autoComplete="email" required maxLength="254" placeholder="you@business.com"/></label></div><div className="form-row"><label>Project type <span>*</span><select name="project_type" required defaultValue=""><option value="" disabled>Select a service</option>{services.map(s=><option key={s.title}>{s.title}</option>)}<option>Something else</option></select></label><label>Budget range<select name="budget" defaultValue=""><option value="">Let’s discuss</option>{budgets.map(b=><option key={b}>{b}</option>)}</select></label></div><label>What would you like to build? <span>*</span><textarea name="message" rows="5" required minLength="10" maxLength="5000" placeholder="A little about your business, your website and what you’d like to achieve…"/></label><div className="honeypot" aria-hidden="true"><label>Leave this field empty<input name="botcheck" tabIndex="-1" autoComplete="off"/></label></div><p className="privacy-note">Your details are only used to respond to your enquiry. Form submissions are processed by Web3Forms.</p><button className="button primary" disabled={state.type==='loading'} type="submit">{state.type==='loading'?'Sending…':'Send Project Enquiry'}</button><p ref={status} role="status" aria-live="polite" className={'form-status '+state.type}>{state.message}</p></form></div></section>
}
