export const owner = { name: 'Vijay Krishna P J', email: 'vijaykrishnapj5@gmail.com', phone: '+91 89213 30633', whatsapp: 'https://wa.me/918921330633', github: 'https://github.com/vijaykrishnapj5-source', linkedin: 'https://www.linkedin.com/in/vijay-krishna-p-j-5a3a68258', photo: '8FC1DA37-1061-449E-ADA4-4EDF8ECEA1A0.PNG', resume: 'resume.pdf' };
export const services = [
 {title:'Business & Landing Page Websites', short:'A clear first impression. A simpler next step.', description:'Responsive websites that explain what you do and make it easy for customers to get in touch.', tag:'For shops, clinics & growing businesses'},
 {title:'Custom Web Apps', short:'Less manual work. More room to grow.', description:'Inventory tools, booking workflows and dashboards built around the way your business works.', tag:'For everyday business operations'},
 {title:'Website Redesign & Speed Optimization', short:'Make your existing website work harder.', description:'Cleaner navigation, mobile-friendly layouts and focused performance improvements.', tag:'For websites ready for a fresh start'},
 {title:'Data Dashboards & Automation', short:'Turn scattered data into useful answers.', description:'Bring information together in clear dashboards and simplify repetitive tasks with practical automation.', tag:'For teams working with data'}
];
export const projects = [
 {id:'inventory',title:'Inventory Management System',category:'Business web application',problem:'Products, orders and stock levels need to stay in sync as a business operates.',solution:'Built a full-stack inventory application with product categorization, order management, stock updates and automated low-stock alerts.',result:'A central workflow for managing products and orders, with low-stock alerts to flag items that need attention. No client deployment or measured business outcome is claimed.',tech:['React','Tailwind CSS','PHP','MySQL'],demo:'',github:''},
 {id:'acoustic',title:'Listening for early signs of failure.',fullTitle:'Hybrid Acoustic Anomaly Detection for Predictive Maintenance',category:'Machine learning · Research project',problem:'Unusual machine sounds can indicate faults that are difficult to identify consistently by listening alone.',solution:'Combined Deep SAD, Autoencoders, LOF, Isolation Forest and One-Class SVM using 111 acoustic features from MIMII and ToyADMOS datasets.',result:'ROC-AUC up to 0.958 on the evaluated datasets. This is a research evaluation, not a production maintenance guarantee.',tech:['Python','TensorFlow','Scikit-learn','Librosa'],demo:'',github:''},
 {id:'churn',title:'Making customer churn easier to understand.',fullTitle:'Telecom Customer Churn Prediction (Big Data)',category:'Big data · Predictive analytics',problem:'Telecom customer data needs a scalable pipeline to identify patterns associated with churn.',solution:'Built an Apache Spark pipeline and trained a Gradient-Boosted Trees model to predict customer churn.',result:'The GBT model reached AUC 0.8561 in evaluation. No commercial retention result is claimed.',tech:['Apache Spark','Machine learning','GBT'],demo:'',github:''}
];
export const process = [ ['Discuss','Tell me about your business, customers and what your website needs to do.'], ['Design & Quote','We agree on the scope, visual direction, timeline and a clear project quote.'], ['Build & Review','I build your website and share progress so we can refine it together.'], ['Launch & Support','We check the details, launch your site and agree on the support you need.'] ];
export const skills = { 'Web development':['HTML','CSS','JavaScript','React','Tailwind CSS','Node.js','PHP','REST APIs'], 'Databases':['MySQL','SQL'], 'Cloud & tools':['AWS · foundational','S3','EC2','Lambda','IAM','API Gateway','Git','VS Code'], 'Data & machine learning':['Python','Scikit-learn','TensorFlow','Apache Spark','Matplotlib','Jupyter'] };
// Budget choices describe planning status, not invented prices or fee estimates.
export const budgets = ['I need guidance','I have a range to discuss','My budget is flexible','I prefer to share it in my message'];
